# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Empirical Study âš—ï¸
      labels:
        - code
    - title: Writing ğŸ“–
      labels:
        - writing
    - title: Other Changes
      labels:
        - "*"